---
name: Workflow

on:
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
        default: ${{ github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  print-env-and-check-yaml:
    timeout-minutes: 60
    runs-on: self-hosted

    steps:
      - run: env
